from .extended_enum import ExtendedEnum


class FormasSal(ExtendedEnum):
    """
    Enumeração das formas de sais e ésteres de compostos químicos.

    Esta classe centraliza os sufixos e variações químicas utilizados para
    identificar a forma de apresentação de substâncias farmacêuticas.
    """

    ACETATO = "acetato"
    ACEPONATO = "aceponato"
    ANTIMONIATO = "antimoniato"
    BENZOATO = "benzoato"
    BESILATO = "besilato"
    BISSULFATO = "bissulfato"
    BROMETO = "brometo"
    BROMIDRATO = "bromidrato"
    BUTILBROMETO = "butilbrometo"
    CARBONATO = "carbonato"
    CITRATO = "citrato"
    CLORETO = "cloreto"
    CLORIDRATO = "cloridrato"
    DECANOATO = "decanoato"
    DIASPARTATO = "diaspartato"
    DICLORIDRATO = "dicloridrato"
    DIMALEATO = "dimaleato"
    DIMESILATO = "dimesilato"
    DIPROPIONATO = "dipropionato"
    EMBONATO = "embonato"
    ETANOLATO = "etanolato"
    ETEXILATO = "etexilato"
    FENDIZOATO = "fendizoato"
    FOSFATO = "fosfato"
    FUMARATO = "fumarato"
    FUROATO = "furoato"
    HEMIFUMARATO = "hemifumarato"
    HEMITARTARATO = "hemitartarato"
    HICLATO = "hiclato"
    HIDROXIBENZOATO = "hidroxibenzoato"
    LACTATO = "lactato"
    LISINATO = "lisinato"
    MALEATO = "maleato"
    MALATO = "malato"
    MESILATO = "mesilato"
    METILSULFATO = "metilsulfato"
    MICOFENOLATO = "micofenolato"
    NITRATO = "nitrato"
    OLEATO = "oleato"
    OXALATO = "oxalato"
    PAMOATO = "pamoato"
    PROPIONATO = "propionato"
    SUCCINATO = "succinato"
    SULFATO = "sulfato"
    TARTARATO = "tartarato"
    TOSILATO = "tosilato"
    VALERATO = "valerato"
