# TODO: A coluna `categorias_de_complementares_por_indicacao` é gerada por um notebook de enriquecimento, então deveria estar presente somente na `produtos_refined`.
schema = """
    id STRING NOT NULL,
    ean STRING NOT NULL,
    eans_alternativos ARRAY<STRING>,
    status STRING,
    nome STRING NOT NULL,
    nomes_alternativos ARRAY<STRING>,
    marca STRING,
    fabricante STRING,
    descricao STRING,
    eh_medicamento BOOLEAN,
    tipo_medicamento STRING,
    indicacao STRING,
    dosagem STRING,
    variantes ARRAY<STRING>,
    principio_ativo STRING,
    eh_tarjado BOOLEAN,
    tarja STRING,
    eh_otc BOOLEAN,
    eh_controlado BOOLEAN,
    categorias ARRAY<STRING>,
    classes_terapeuticas ARRAY<STRING>,
    especialidades ARRAY<STRING>,
    imagem_url STRING,
    categorias_de_complementares_por_indicacao ARRAY<STRUCT<
      indicacao STRING,
      categorias ARRAY<STRING>
    >>,
    informacoes_para_embeddings STRING,
    tipo_de_receita_completo STRING,
    descontinuado boolean,
    pode_partir boolean,
    numero_registro string,
    idade_recomendada string,
    doencas_relacionadas array<string>,
    temperatura_armazenamento string,
    via_administracao string,
    uso_continuo boolean,
    bula STRING,
    fonte STRING,
    gerado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
"""
