# NOTE: Esse schema não é o mesmo da tabela _produtos_em_processamento!

schema = """
    id STRING NOT NULL,
    ean STRING NOT NULL,
    eans_alternativos ARRAY<STRING>,
    status STRING,
    nome STRING,
    nomes_alternativos ARRAY<STRING>,
    marca STRING,
    fabricante STRING,
    descricao STRING,
    eh_medicamento BOOLEAN,
    tipo_medicamento STRING,
    indicacao STRING,
    dosagem STRING,
    variantes ARRAY<STRING>,
    principio_ativo STRING,
    tarja STRING,
    eh_tarjado BOOLEAN,
    eh_controlado BOOLEAN,
    eh_generico BOOLEAN,
    categorias ARRAY<STRING>,
    classes_terapeuticas ARRAY<STRING>,
    especialidades ARRAY<STRING>,
    imagem_url STRING,
    categorias_de_complementares_por_indicacao ARRAY<STRUCT<
      indicacao STRING,
      categorias ARRAY<STRING>
    >>,
    nome_comercial STRING,
    eh_otc BOOLEAN,
    medicamentos_referencia STRING,
    medicamentos_similares STRING,
    contraindicacoes STRING,
    efeitos_colaterais STRING,
    interacoes_medicamentosas STRING,
    instrucoes_de_uso STRING,
    advertencias_e_precaucoes STRING,
    condicoes_de_armazenamento STRING,
    validade_apos_abertura STRING,
    validade_receita_dias BIGINT,
    tipo_receita STRING,
    tipo_de_receita_completo STRING,
    forma_farmaceutica STRING,
    via_administracao STRING,
    volume_quantidade STRING,
    descontinuado boolean,
    pode_partir boolean,
    numero_registro string,
    doencas_relacionadas array<string>,
    temperatura_armazenamento string,
    uso_continuo boolean,
    tamanho_produto STRING,
    idade_recomendada STRING,
    sexo_recomendado STRING,
    informacoes_para_embeddings STRING,
    fonte STRING,
    bula STRING,
    tags_complementares ARRAY<STRING>,
    tags_substitutos ARRAY<STRING>,
    tags_potencializam_uso ARRAY<STRING>,
    tags_atenuam_efeitos ARRAY<STRING>,
    tags_agregadas ARRAY<STRING>,
    power_phrase STRING,
    lojas_com_produto STRING,
    ids_lojas_com_produto ARRAY<STRING>,
    categorias_recomendadas ARRAY<STRING>,
    quality_score DOUBLE,
    gerado_em TIMESTAMP NOT NULL,
    atualizado_em TIMESTAMP NOT NULL
"""
