schema = """
    ean STRING NOT NULL,
    eans_alternativos ARRAY<STRING>,
    nome STRING NOT NULL,
    marca STRING,
    nome_complemento STRING,
    fabricante STRING,
    descricao STRING,
    eh_medicamento BOOLEAN,
    tipo_medicamento STRING,
    dosagem STRING,
    variantes ARRAY<STRING>,
    principio_ativo STRING,
    eh_tarjado BOOLEAN,
    tarja STRING,
    eh_otc BOOLEAN,
    eh_controlado BOOLEAN,
    categorias ARRAY<STRING>,
    classes_terapeuticas ARRAY<STRING>,
    especialidades ARRAY<STRING>,
    imagem_url STRING,
    arquivo_s3 STRING,
    bula ARRAY<STRUCT<
        id STRING,
        title STRING,
        content STRING
    >>,
    tipo_de_receita_completo STRING,
    descontinuado boolean,
    pode_partir boolean,
    numero_registro string,
    idade_recomendada string,
    doencas_relacionadas array<string>,
    temperatura_armazenamento string,
    via_administracao string,
    uso_continuo boolean,
    fonte STRING,
    gerado_em timestamp
"""
