# Referencias ingressantes:
# - https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/prompt-optimizer?hl=pt-br
# - https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/prompt-design-strategies?hl=pt-br
# - https://ai.google.dev/gemini-api/docs/prompting-strategies?hl=pt-br

from .alimentos_suplementos import (
    PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE,
    PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE_SYSTEM,
    PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE_USER_TEMPLATE,
)
from .categorias import get_prompt_categorias
from .enriquecimento import (
    MAGGU_SYSTEM_INSTRUCTION,
    MAGGU_SYSTEM_PROMPT,
    MAGGU_USER_TEMPLATE,
)
from .eval_puro_alternativos import (
    EVAL_ALTERNATIVOS_MEDICAMENTO_PROMPT,
    EVAL_ALTERNATIVOS_NAO_MEDICAMENTO_PROMPT,
    EVAL_ALTERNATIVOS_SYSTEM,
)
from .llm_judge import (
    LLM_JUDGE_EVALUATION_PROMPT,
    LLM_JUDGE_SYSTEM_INSTRUCTION_TEMPLATE,
    LLM_JUDGE_USER_TEMPLATE,
)
from .materiais_saude import (
    PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE,
    PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE_SYSTEM,
    PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE_USER_TEMPLATE,
)
from .perfumaria_cuidados import (
    PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS,
    PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS_SYSTEM,
    PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS_USER_TEMPLATE,
)
from .power_phrase import (
    POWER_PHRASE_PROMPT,
    POWER_PHRASE_SYSTEM_INSTRUCTION,
    POWER_PHRASE_USER_TEMPLATE,
)
from .produtos_animais import (
    PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS,
    PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS_SYSTEM,
    PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS_USER_TEMPLATE,
)
from .produtos_casa import (
    PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA,
    PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA_SYSTEM,
    PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA_USER_TEMPLATE,
)
from .resume_indicacao import (
    RESUME_INDICACAO_PROMPT,
    RESUME_INDICACAO_SYSTEM_INSTRUCTION,
    RESUME_INDICACAO_USER_TEMPLATE,
)
from .sintomas_categorias_complementares import (
    PROMPT_CATEGORIAS_POR_SINTOMA,
    PROMPT_CATEGORIAS_SYSTEM_INSTRUCTION,
    PROMPT_CATEGORIAS_USER_TEMPLATE,
    PROMPT_SINTOMAS_PRODUTO,
    PROMPT_SINTOMAS_SYSTEM_INSTRUCTION,
    PROMPT_SINTOMAS_USER_TEMPLATE,
)
from .tags_produto import (
    TAGS_PROMPT_TEMPLATE,
    TAGS_SYSTEM_INSTRUCTION_TEMPLATE,
    TAGS_USER_TEMPLATE,
)
from .websearch_marca_fabricante import MARCA_FABRICANTE_PROMPT_INSTRUCTIONS

__all__ = [
    # Prompts por categoria de produto (originais + splits para caching)
    "PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE",
    "PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE_SYSTEM",
    "PROMPT_ENRIQUECIMENTO_ALIMENTOS_SAUDE_USER_TEMPLATE",
    "PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE",
    "PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE_SYSTEM",
    "PROMPT_ENRIQUECIMENTO_MATERIAIS_SAUDE_USER_TEMPLATE",
    "PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS",
    "PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS_SYSTEM",
    "PROMPT_ENRIQUECIMENTO_PERFUMARIA_CUIDADOS_USER_TEMPLATE",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS_SYSTEM",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_ANIMAIS_USER_TEMPLATE",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA_SYSTEM",
    "PROMPT_ENRIQUECIMENTO_PRODUTOS_CASA_USER_TEMPLATE",
    # Prompts gerais (originais + splits para caching)
    "get_prompt_categorias",
    "EVAL_ALTERNATIVOS_MEDICAMENTO_PROMPT",
    "EVAL_ALTERNATIVOS_NAO_MEDICAMENTO_PROMPT",
    "EVAL_ALTERNATIVOS_SYSTEM",
    "LLM_JUDGE_EVALUATION_PROMPT",
    "LLM_JUDGE_SYSTEM_INSTRUCTION_TEMPLATE",
    "LLM_JUDGE_USER_TEMPLATE",
    "MAGGU_SYSTEM_PROMPT",
    "MAGGU_SYSTEM_INSTRUCTION",
    "MAGGU_USER_TEMPLATE",
    "MARCA_FABRICANTE_PROMPT_INSTRUCTIONS",
    "POWER_PHRASE_PROMPT",
    "POWER_PHRASE_SYSTEM_INSTRUCTION",
    "POWER_PHRASE_USER_TEMPLATE",
    "RESUME_INDICACAO_PROMPT",
    "RESUME_INDICACAO_SYSTEM_INSTRUCTION",
    "RESUME_INDICACAO_USER_TEMPLATE",
    "TAGS_PROMPT_TEMPLATE",
    "TAGS_SYSTEM_INSTRUCTION_TEMPLATE",
    "TAGS_USER_TEMPLATE",
    # Sintomas e categorias complementares
    "PROMPT_SINTOMAS_PRODUTO",
    "PROMPT_SINTOMAS_SYSTEM_INSTRUCTION",
    "PROMPT_SINTOMAS_USER_TEMPLATE",
    "PROMPT_CATEGORIAS_POR_SINTOMA",
    "PROMPT_CATEGORIAS_SYSTEM_INSTRUCTION",
    "PROMPT_CATEGORIAS_USER_TEMPLATE",
]
