configs = {
    "production": {
        "name": "production",
        "name_short": "prod",
        "catalog": "production",
        "bucket": "maggu-datalake-prod",
        "postgres_host": "maggu-poc.cbgww662dsmx.us-east-1.rds.amazonaws.com",
        "postgres_replica_host": "maggu-readreplica.cbgww662dsmx.us-east-1.rds.amazonaws.com",
        "postgres_port": 5432,
        "postgres_database": "maggu_production",
        "postgres_user": "datalake",
        "data_api_url": "https://data-api.maggu.ai",
        "bigdatacorp_address": "https://plataforma.bigdatacorp.com.br/",
        "bluesoft_address": "https://api.cosmos.bluesoft.com.br/",
        "portal_obm_address": "https://portal-obm.saude.gov.br/api/",
        "postgres_schema": "bigquery.postgres_public",
        "databricks_views_schema": "bigquery.databricks_views_production",
    },
    "staging": {
        "name": "staging",
        "name_short": "dev",
        "catalog": "staging",
        "bucket": "maggu-datalake-dev",
        "postgres_host": "copilot-staging.cbgww662dsmx.us-east-1.rds.amazonaws.com",
        "postgres_replica_host": None,
        "postgres_port": 5432,
        "postgres_database": "copilot_staging",
        "postgres_user": "datalake",
        "data_api_url": "https://staging.data-api.maggu.ai",
        "bigdatacorp_address": "https://plataforma.bigdatacorp.com.br/",
        "bluesoft_address": "https://api.cosmos.bluesoft.com.br/",
        "portal_obm_address": "https://portal-obm.saude.gov.br/api/",
        "postgres_schema": "bigquery.postgres_staging_public",
        "databricks_views_schema": "bigquery.databricks_views_staging",
    },
}
